### ISSUE TITLE
Connect apis: `sennight-fastapi` and `sennight-smoking-log-fastapi`

### ISSUE THREAD

**Issue by haneujeen** [haneujeen/sennight#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sykr1313** [comment]
두 서버가 api를 통해 연결되나요? sennight-smoking-log-fastapi  api 명세서에 추가 부탁드립니다

**Comment by haneujeen** [comment]
> 두 서버가 api를 통해 연결되나요? sennight-smoking-log-fastapi api 명세서에 추가 부탁드립니다

#20 SmokingLog 모델이 사용자 id를 외래키로 가지기 때문에 공유되는 JWT secret과 알고리즘을 통한 검증 미들웨어를 추가했습니다. 서버 간 엔드포인트를 통한 연결 또는 두번째 서버에서 배포된 데이터베이스에 직접 접근해서 사용자 id를 검증하는 방법도 있습니다.
